languageCode = "en-GB"
title = "I ♡ SOFTWARE"
baseurl = "https://i.love.software/"
theme = "i-love-software"

[Author]
  name = "David Herrmann"

[Params]
  description = "code by David Herrmann"
  twitter = "https://twitter.com/davherrmann"
  github = "https://github.com/davherrmann"
  disqus = "davherrmann"
  copyright = "© David Herrmann"

[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "/post/"
